[package]
name = "sharedstate"
version = "2.0.1"
edition = "2024"
authors = ["Patrick Lorio <patrick@methods.dev>"]
description = "Sync heavily read state across many servers"
repository = "https://github.com/Developed-Methods/sharedstate"
license-file = "LICENSE.txt"

[dependencies]
arc-metrics = "0.1.4"
message-encoding = "0.2.4"
sequenced-broadcast = "0.3.0"
tokio = { version = "1.40", features = ["full"] }
tokio-util = "0.7.12"
futures-util = "0.3.31"
tracing = "0.1.40"
hotread = "0.1.1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.40", features = ["full", "test-util"] }
tracing-subscriber = "0.3"
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm", "std"] }
crossterm = "0.29.0"
unicode-width = "0.2.2"
